name: Run and Auto-Save Kali VNC Container

on:
  workflow_dispatch:

jobs:
  run-and-save-session:
    runs-on: ubuntu-latest
    timeout-minutes: 3600 # 6 hours

    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      SSH_PASS: ${{ secrets.SSH_PASS }}

    steps:
      - name: Login to Docker Hub
        run: |
          echo "Logging in to Docker Hub..."
          echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin

      - name: Pull and Run Container
        run: |
          IMAGE_NAME="$DOCKERHUB_USERNAME/kali_linux:autov1"
          echo "Pulling latest image: $IMAGE_NAME"
          docker pull "$IMAGE_NAME"

          echo "Starting container with full privileges..."
          docker run -d --name=kali-session \
            --privileged \
            --volume ~/shared_storage:/root/shared \
            "$IMAGE_NAME" tail -f /dev/null

      - name: Create Helper and Startup Scripts
        run: docker exec kali-session chmod +x /start.sh

      - name: Start Services and Auto-Save Process
        run: |
          echo "Executing '/start.sh' in the container to launch services..."
          docker exec kali-session bash /start.sh &

          (
            sleep 19800 # 5.5 hours in seconds
            echo "[Auto-Save] Committing container state..."
            docker commit kali-session "$DOCKERHUB_USERNAME/kali_linux:autov1"
            echo "[Auto-Save] Pushing new image to Docker Hub..."
            docker push "$DOCKERHUB_USERNAME/kali_linux:autov1"
            echo "[Auto-Save] Session state saved!"
          ) &

      - name: Display Info
        run: |
          echo "=============================================================="
          echo " SESSION IS READY"
          echo " SSH password stored in env var SSH_PASS for tmate access"
          echo "=============================================================="

      - name: Start tmate SSH Session
        uses: mxschmitt/action-tmate@v3
        env:
          TMATE_SSH_PASS: ${{ secrets.SSH_PASS }}

      - name: Keep Workflow Alive & Auto-Restart
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          start_time=$(date +%s)
          max_runtime=$((5 * 60 * 60 + 50 * 60)) # 5h 50m in seconds
          
          while true; do
            now=$(date +%s)
            uptime=$((now - start_time))
            echo "[$(date)] Uptime: $((uptime / 60)) minutes"

            if [ "$uptime" -ge "$max_runtime" ]; then
              echo "[$(date)] Restarting workflow (auto-trigger)..."

              # Use GitHub API to trigger same workflow again
              curl -X POST \
                -H "Accept: application/vnd.github+json" \
                -H "Authorization: Bearer $GH_TOKEN" \
                https://api.github.com/repos/${{ github.repository }}/actions/workflows/main.yml/dispatches \
                -d '{"ref":"main"}'

              echo "Workflow re-triggered. Exiting this one..."
              exit 0
            fi

            sleep 180  # check every 3 minutes
          done
